post:
  operationId: upload
  summary: Upload an application to enterprise
  description: Returns application
  produces:
    - application/json
  parameters:
    - name: app_file
      description: Valid APK file
      in: formData
      required: true
      type: file
  responses:
    '201':
      description: Successful operation
      schema:
        type: object
        properties:
          application:
            $ref: '#/definitions/Application'
  consumes:
    - multipart/form-data
    - application/x-www-form-urlencoded
  security:
    - apiKey: []
  tags:
    - Application
parameters:
  - name: enterprise_id
    description: A UUID string identifying this enterprise.
    in: path
    required: true
    type: string